#Modpack Configuration Settings
["Custom server in multiplayer Screen"]
	#Name of the server
	"Server Name" = "Official Public Server"
	#IP of the server
	"Server IP" = "farmopolis.benbenlaw.com"

["Discord URL use /discord command to get the link"]
	#Add a URL to link your discord, BBL Discord = https://discord.gg/benbenlaw
	"Discord URL" = "https://discord.gg/benbenlaw"

["Modpack information handy for modpack makers use /modpack in game to get the information"]
	#Modpack name
	"Modpack name" = "Farmopolis"
	#Modpack Version
	"Modpack Version" = "3.1"

["Check if the modpack has any updates available"]
	#Check if the modpack has any updates available, default = false
	"Update Checker" = true
	#Project ID for the modpack, found on curse forge
	"Project ID" = 1270262
