ServerEvents.recipes(event => {

    //Mystical Essence to Molten Fluids
    event.recipes.casting.melting('mysticalagriculture:iron_essence', '45x casting:molten_iron', 1000).id(`farmopolis:casting/melting/iron_essence`)
    event.recipes.casting.melting('mysticalagriculture:gold_essence', '45x casting:molten_gold', 1000).id(`farmopolis:casting/melting/gold_essence`)
    event.recipes.casting.melting('mysticalagriculture:copper_essence', '45x casting:molten_copper', 1000).id(`farmopolis:casting/melting/copper_essence`)
    event.recipes.casting.melting('mysticalagriculture:tin_essence', '45x casting:molten_tin', 1000).id(`farmopolis:casting/melting/tin_essence`)
    event.recipes.casting.melting('mysticalagriculture:lapis_lazuli_essence', '45x casting:molten_lapis', 1000).id(`farmopolis:casting/melting/lapis_essence`)
    event.recipes.casting.melting('mysticalagriculture:diamond_essence', '45x casting:molten_diamond', 1000).id(`farmopolis:casting/melting/diamond_essence`)
    event.recipes.casting.melting('mysticalagriculture:emerald_essence', '45x casting:molten_emerald', 1000).id(`farmopolis:casting/melting/emerald_essence`)
    event.recipes.casting.melting('mysticalagriculture:coal_essence', '40x casting:molten_coal', 1000).id(`farmopolis:casting/melting/coal_essence`)
    event.recipes.casting.melting('mysticalagriculture:zinc_essence', '45x casting:molten_zinc', 1000).id(`farmopolis:casting/melting/zinc_essence`)
    event.recipes.casting.melting('mysticalagriculture:osmium_essence', '45x casting:molten_osmium', 1000).id(`farmopolis:casting/melting/osmium_essence`)
    event.recipes.casting.melting('mysticalagriculture:uranium_essence', '45x casting:molten_uranium', 1000).id(`farmopolis:casting/melting/uranium_essence`)
    event.recipes.casting.melting('mysticalagriculture:nether_quartz_essence', '125x casting:molten_quartz', 1000).id(`farmopolis:casting/melting/nether_quartz_essence`)
    event.recipes.casting.melting('mysticalagriculture:bronze_essence', '45x casting:molten_bronze', 1000).id(`farmopolis:casting/melting/bronze_essence`)
    event.recipes.casting.melting('mysticalagriculture:ruby_essence', '45x casting:molten_ruby', 1000).id(`farmopolis:casting/melting/ruby_essence`)
    event.recipes.casting.melting('mysticalagriculture:sapphire_essence', '45x casting:molten_sapphire', 1000).id(`farmopolis:casting/melting/sapphire_essence`)
    event.recipes.casting.melting('mysticalagriculture:peridot_essence', '45x casting:molten_peridot', 1000).id(`farmopolis:casting/melting/peridot_essence`)
    event.recipes.casting.melting('mysticalagriculture:aluminum_essence', '45x casting:molten_aluminum', 1000).id(`farmopolis:casting/melting/aluminum_essence`)
    event.recipes.casting.melting('mysticalagriculture:redstone_essence', '45x casting:molten_redstone', 1000).id(`farmopolis:casting/melting/redstone_essence`)
    event.recipes.casting.melting('mysticalagriculture:nickel_essence', '45x casting:molten_nickel', 1000).id(`farmopolis:casting/melting/nickel_essence`)
    event.recipes.casting.melting('mysticalagriculture:lead_essence', '45x casting:molten_lead', 1000).id(`farmopolis:casting/melting/lead_essence`)
    event.recipes.casting.melting('mysticalagriculture:silver_essence', '45x casting:molten_silver', 1000).id(`farmopolis:casting/melting/silver_essence`)
    event.recipes.casting.melting('mysticalagriculture:iridium_essence', '45x casting:molten_iridium', 1000).id(`farmopolis:casting/melting/iridium_essence`)
    event.recipes.casting.melting('mysticalagriculture:black_quartz_essence', '125x casting:molten_black_quartz', 1000).id(`farmopolis:casting/melting/black_quartz_essence`)
    event.recipes.casting.melting('mysticalagriculture:platinum_essence', '45x casting:molten_platinum', 1000).id(`farmopolis:casting/melting/platinum_essence`)
    event.recipes.casting.melting('mysticalagriculture:quartz_enriched_iron_essence', '45x casting:molten_quartz_enriched_iron', 1000).id(`farmopolis:casting/melting/quartz_enriched_iron_essence`)
    event.recipes.casting.melting('mysticalagriculture:netherite_essence', '45x casting:molten_netherite', 1000).id(`farmopolis:casting/melting/netherite_essence`)
    event.recipes.casting.melting('mysticalagriculture:glowstone_essence', '125x casting:molten_glowstone', 1000).id(`farmopolis:casting/melting/glowstone_essence`)
    event.recipes.casting.melting('mysticalagriculture:brass_essence', '45x casting:molten_brass', 1000).id(`farmopolis:casting/melting/brass_essence`)



    event.smelting('3x minecraft:iron_nugget', 'mysticalagriculture:iron_essence').id(`farmopolis:smelting/iron_essence`)
    event.smelting('3x minecraft:gold_nugget', 'mysticalagriculture:gold_essence').id(`farmopolis:smelting/gold_essence`)
    event.smelting('3x alltheores:copper_nugget', 'mysticalagriculture:copper_essence').id(`farmopolis:smelting/copper_essence`)
    event.smelting('3x alltheores:tin_nugget', 'mysticalagriculture:tin_essence').id(`farmopolis:smelting/tin_essence`)
    event.smelting('3x alltheores:zinc_nugget', 'mysticalagriculture:zinc_essence').id(`farmopolis:smelting/zinc_essence`)
    event.smelting('3x alltheores:osmium_nugget', 'mysticalagriculture:osmium_essence').id(`farmopolis:smelting/osmium_essence`)
    event.smelting('3x alltheores:uranium_nugget', 'mysticalagriculture:uranium_essence').id(`farmopolis:smelting/uranium_essence`)
    event.smelting('3x alltheores:bronze_nugget', 'mysticalagriculture:bronze_essence').id(`farmopolis:smelting/bronze_essence`)
    event.smelting('3x alltheores:aluminum_nugget', 'mysticalagriculture:aluminum_essence').id(`farmopolis:smelting/aluminum_essence`)
    event.smelting('3x alltheores:nickel_nugget', 'mysticalagriculture:nickel_essence').id(`farmopolis:smelting/nickel_essence`)
    event.smelting('3x alltheores:lead_nugget', 'mysticalagriculture:lead_essence').id(`farmopolis:smelting/lead_essence`)
    event.smelting('3x alltheores:silver_nugget', 'mysticalagriculture:silver_essence').id(`farmopolis:smelting/silver_essence`)
    event.smelting('3x alltheores:iridium_nugget', 'mysticalagriculture:iridium_essence').id(`farmopolis:smelting/iridium_essence`)
    event.smelting('3x alltheores:platinum_nugget', 'mysticalagriculture:platinum_essence').id(`farmopolis:smelting/platinum_essence`)

})