#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Feb 22 13:06:53 GMT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.6.1 + Clrwl_1.0.2.zip
