name: Generate Mod Changelog

on:
  push:
    paths:
      - "changelogs/manifest.json"

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # needed for HEAD^

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run changelog generator
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: python changelogs/generate_changelog.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add changelogs/*.md cf_cache.json
          git commit -m "Update mod changelog" || echo "No changes"
          git push
